version: '3'
services:
  formalog_database:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: drupal_db
    volumes:
      - shared_volume:/backup

  formalog_drupal:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 3389:80
    depends_on:
      - formalog_database
    environment:
      DRUPAL_DATABASE_HOST: db
      DRUPAL_DATABASE_NAME: drupal_db
      DRUPAL_DATABASE_USER: root
      DRUPAL_DATABASE_PASSWORD: example
    volumes:
      - ./src:/opt/drupal/
      - shared_volume:/backup

  formalog_phpmyadmin:
    image: arm64v8/phpmyadmin
    environment:
      PMA_HOST: db
      PHP_UPLOAD_MAX_FILESIZE: 1G
      PHP_MAX_INPUT_VARS: 1G
      PMA_ARBITRARY: 1
      UPLOAD_LIMIT: 140G
      MAX_EXECUTION_TIME: 256998
      MEMORY_LIMIT: 140G
      MYSQL_ROOT_PASSWORD: example
    ports:
      - 3388:80

volumes:
  shared_volume:
  src: